/*
 * Copyright: (c) 2024, Alex Kaul
 * GNU General Public License v3.0 or later (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
 */

/**
 * @fileoverview
 * Global click-hold-and-drag scrolling: press the left mouse button on any
 * scrollable area (workflow tabs, shelf, lists, settings screens, ...) and
 * drag to pan it, like grabbing the content on a touch screen.
 * Interactive and draggable elements are left alone so text inputs, buttons,
 * drag-and-drop reordering and widget resizing keep working.
 */

// don't start a pan from elements that have their own pointer interactions
const skipSelector = [
  'input', 'textarea', 'select', 'button', 'a[href]', 'option',
  '[contenteditable="true"]', '[contenteditable="plaintext-only"]',
  '[draggable="true"]',
  '[data-testid="widget-layout-item-resize-handle"]',
  '[data-no-drag-scroll]',
  'webview', 'iframe'
].join(', ');

const dragThresholdPx = 5;

function findScrollableAncestor(el: Element | null): HTMLElement | null {
  while (el && el !== document.body && el instanceof HTMLElement) {
    const canScrollX = el.scrollWidth > el.clientWidth + 1;
    const canScrollY = el.scrollHeight > el.clientHeight + 1;
    if (canScrollX || canScrollY) {
      const style = window.getComputedStyle(el);
      const scrollableX = canScrollX && /auto|scroll|overlay/.test(style.overflowX);
      const scrollableY = canScrollY && /auto|scroll|overlay/.test(style.overflowY);
      if (scrollableX || scrollableY) {
        return el;
      }
    }
    el = el.parentElement;
  }
  return null;
}

export function installDragScroll(): () => void {
  let scrollEl: HTMLElement | null = null;
  let startX = 0;
  let startY = 0;
  let startLeft = 0;
  let startTop = 0;
  let dragging = false;

  const suppressClick = (e: MouseEvent) => {
    e.stopPropagation();
    e.preventDefault();
  };

  const endDrag = () => {
    if (dragging) {
      document.body.style.removeProperty('user-select');
      document.body.style.removeProperty('cursor');
      // swallow the click generated by releasing the button after a pan
      window.addEventListener('click', suppressClick, { capture: true, once: true });
      setTimeout(() => window.removeEventListener('click', suppressClick, { capture: true }), 0);
    }
    scrollEl = null;
    dragging = false;
    window.removeEventListener('pointermove', onPointerMove);
    window.removeEventListener('pointerup', onPointerUp);
    window.removeEventListener('pointercancel', onPointerUp);
  };

  const onPointerMove = (e: PointerEvent) => {
    if (!scrollEl) {
      return;
    }
    const dx = e.clientX - startX;
    const dy = e.clientY - startY;
    if (!dragging) {
      if (Math.abs(dx) < dragThresholdPx && Math.abs(dy) < dragThresholdPx) {
        return;
      }
      dragging = true;
      document.body.style.userSelect = 'none';
      document.body.style.cursor = 'grabbing';
    }
    scrollEl.scrollLeft = startLeft - dx;
    scrollEl.scrollTop = startTop - dy;
  };

  const onPointerUp = () => endDrag();

  const onPointerDown = (e: PointerEvent) => {
    if (e.button !== 0 || e.pointerType !== 'mouse') {
      return;
    }
    const target = e.target;
    if (!(target instanceof Element) || target.closest(skipSelector)) {
      return;
    }
    const el = findScrollableAncestor(target);
    if (!el) {
      return;
    }
    scrollEl = el;
    startX = e.clientX;
    startY = e.clientY;
    startLeft = el.scrollLeft;
    startTop = el.scrollTop;
    dragging = false;
    window.addEventListener('pointermove', onPointerMove);
    window.addEventListener('pointerup', onPointerUp);
    window.addEventListener('pointercancel', onPointerUp);
  };

  window.addEventListener('pointerdown', onPointerDown);
  return () => {
    window.removeEventListener('pointerdown', onPointerDown);
    endDrag();
  };
}
